### PR TITLE
#7 Terraform "depends_on" does not wait - wait_timeout resource schema added.

### PR DESCRIPTION
**Pull request by virajindasrao**
wait_timeout resource schema added and the default value is 15 minutes.
value can be changed by adding wait_timeout schema into terraform resource configuration.

Signed-off-by: Viraj Indasrao <virajindasrao@gmail.com>

### CODE REVIEW

**Comment by Marcvd316** [comment]
Hi @virajindasrao , could you provide an example of a tf configuration file that uses the "depends_on" and configures the "wait_timeout" and what the expected behavior is for each?

Thanks!

**Comment by andyxuan2010** [comment]
It seems the depends_on and wait_timeout works in my tests.

**Comment by virajindasrao** [comment]
Here are the examples of wait_timeout. Depends_on is a schema provided by terraform which is used to create dependent resources. I have added wait_timeout schema which will wait for 15 mins by default to come up resource in success state. Example with default value is as follows
Example 1
```
resource "vra7_resource" "machine1" {
  count            = 1
  catalog_name = "CentOS 7.0 x64"
}

resource "vra7_resource" "machine2" {
  count            = 1
  catalog_name = "CentOS 7.0 x64"
  depends_on = ["vra7_resource.machine1"]
}

```
In case, if parent resource is taking more/less time than 15 mins then user can change the value of wait_timeout as follows
Example 2
```
resource "vra7_resource" "machine1" {
  count            = 1
  catalog_name = "CentOS 7.0 x64"
  wait_timeout = 20
}

resource "vra7_resource" "machine2" {
  count            = 1
  catalog_name = "CentOS 7.0 x64"
  depends_on = ["vra7_resource.machine1"]
}

```
Expected change at execution level -
Each resource will wait for 15 mins to come in success state. After wait_timeout time elapsed, resource goes in a failure state or stays in an in_progress state then terraform will throw an error (In case of an in_progress state, a resource will not be deleted from terraform state file. User have to refresh the state to check the progress of the request.).

**Review by nferro — APPROVED** [review]

**Comment by nferro** [comment]
Can you also update the `README.md` to document this?

**Review by markpeek — APPROVED** [review]
Looks good. I added an extra example and fixed gofmt.

**Pull request merged**
